---
#enter the path to your github repository that contains your website 
# you wish to deploy to the server
## for example, 
### repository: https://github.com/shajiakhan/3820-6820-demo.git
repository: https://github.com/shajiakhan/3820-6820-demo.git